name: 04 - Uso de Actions
<<<<<<< HEAD
on: push
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Using the Checkout Action
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: 'Node Setup'
        uses: actions/setup-node@v4
      - name: 'Install Dependencies'
        working-directory: ./my-app
        run: "npm ci"
      - name: Build
        working-directory: ./my-app
        run: "npm run build"
      - name: Test
        working-directory: ./my-app
        run: "npm run test"
=======
on: workflow_dispatch
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: 'Checkout Code'          
         uses: actions/checkout@v4
         
       - name: 'Node Setup'
         uses: actions/setup-node@v4
         with:
           node-version: '24.x'

       - name: 'Install Dependencies'
         working-directory: ./my-app
         run: |            
            npm ci

       - name: 'Run Unit Tests'
         working-directory: ./my-app
         run: |            
            npm run test
        
       
       
>>>>>>> 00f267feaa738e1d365d59056493802a43c5d881
